# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a448cc3435388991fbe994ec76019a4ffb2d03e5186d1bcb925f4592cf0dca7c913bf1d628d42863796f18581b1506351d7a9fc44438ff961f41f841d71402fc

test:
  secret_key_base: 7230f17c833787193b657c40b13e512188caf47022b699ed96511cd3ef56e7c06d0c5b6d4c7f6ed4f6b3ef0256ef21ca3057d9058d994403de2ff4cbbefcee70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
